runtime: go120 

service_account: secret-manager-accessor@green-analog-374311.iam.gserviceaccount.com

env_variables:
  APP_ENV: "production"
  ID_PROJECT: "green-analog-374311"

handlers:
- url: /.*
  script: auto
