runtime: go120 

service_account: secret-manager-accessor@green-analog-374311.iam.gserviceaccount.com

env_variables:
  APP_ENV: "production"
  PROJECT_ID: "green-analog-374311"
  TOPIC_ID: "send-email-topic"
  DEVELOPER_EMAIL: "camilo@camiloengineer.com"

handlers:
- url: /.*
  script: auto
