name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  setup_and_deploy:
    name: Setup and Deploy to GAE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
    
    - name: Install dependencies
      run: go mod download
    
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: green-analog-374311
        export_default_credentials: true
    
    - name: Deploy to App Engine
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-
        gcloud app deploy app.yaml --quiet

