name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  setup_and_deploy:
    name: Setup and Deploy to GAE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
    
    - name: Install dependencies
      run: go mod download

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Check Endpoint
      run: |
        RESPONSE=$(curl --max-time 10 --write-out '%{http_code}' --silent --output /dev/null$ {{ secrets.APP_URL }})
        
        if [ $RESPONSE -eq 200 ]; then
          echo "Endpoint is healthy!"
        else
          echo "Failed to connect to Endpoint! HTTP Status code: $RESPONSE"
          exit 1
        fi
