name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  setup_and_deploy:
    name: Setup and Deploy to GAE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
    
    - name: Install dependencies
      run: go mod download

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_SA_KEY }}