name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  setup_and_deploy:
    name: Setup and Deploy to GAE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
    
    - name: Install dependencies
      run: go mod download

    - name: Setup environment variables from secrets
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST_SECRET }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER_SECRET }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_SECRET }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME_SECRET }}" >> $GITHUB_ENV
        echo "DB_PORT=${{ secrets.DB_PORT_SECRET }}" >> $GITHUB_ENV

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Verify Deployment
      run: |
        sleep 60  # wait a minute to let the service start
        curl -f https://${{ secrets.GCP_PROJECT }}.uc.r.appspot.com
